In [3]:
from numpy import *

arr= array([23,45,44,56,96,76,88])

print(arr)


[23 45 44 56 96 76 88]


In [5]:
from numpy import *

arr= array([23,56.65,54,55,34,66,23.56])
print(arr.dtype)


float64


In [7]:
from numpy import *

arr= array([3,5,6,8,90,44])
print(arr.dtype)


int32


In [10]:
#Function 

from numpy import *
np= linspace(20,90,num=100)
print(np)


[20.         20.70707071 21.41414141 22.12121212 22.82828283 23.53535354
 24.24242424 24.94949495 25.65656566 26.36363636 27.07070707 27.77777778
 28.48484848 29.19191919 29.8989899  30.60606061 31.31313131 32.02020202
 32.72727273 33.43434343 34.14141414 34.84848485 35.55555556 36.26262626
 36.96969697 37.67676768 38.38383838 39.09090909 39.7979798  40.50505051
 41.21212121 41.91919192 42.62626263 43.33333333 44.04040404 44.74747475
 45.45454545 46.16161616 46.86868687 47.57575758 48.28282828 48.98989899
 49.6969697  50.4040404  51.11111111 51.81818182 52.52525253 53.23232323
 53.93939394 54.64646465 55.35353535 56.06060606 56.76767677 57.47474747
 58.18181818 58.88888889 59.5959596  60.3030303  61.01010101 61.71717172
 62.42424242 63.13131313 63.83838384 64.54545455 65.25252525 65.95959596
 66.66666667 67.37373737 68.08080808 68.78787879 69.49494949 70.2020202
 70.90909091 71.61616162 72.32323232 73.03030303 73.73737374 74.44444444
 75.15151515 75.85858586 76.56565657 77.27272727 77.

In [11]:
from numpy import *
np= arange(0,80,5)
print (np)


[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75]


In [12]:
from numpy import * 
np= logspace(20,30,10)
print(np)


[1.00000000e+20 1.29154967e+21 1.66810054e+22 2.15443469e+23
 2.78255940e+24 3.59381366e+25 4.64158883e+26 5.99484250e+27
 7.74263683e+28 1.00000000e+30]


In [13]:
from numpy import *
np= zeros(40)
print(np)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
from numpy import *
np= array([1,2,4,5])
ps= array([2,4,6,8])
arr= np+ps
print(arr)


[ 3  6 10 13]


In [23]:
from numpy import *
np = array([ [2,5,8,9],
  [3,9,8,9]
           ]) 
print(np)

print(np.ndim)




[[2 5 8 9]
 [3 9 8 9]]
2
